// Generated by 'unplugin-vue-components'
// We suggest not to edit this file manually

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
        AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
        AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
        LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
        ErrorAlert: typeof import('./components/common/ErrorAlert.vue')['default']
        SuccessToast: typeof import('./components/common/SuccessToast.vue')['default']
        ConfirmModal: typeof import('./components/common/ConfirmModal.vue')['default']
        DataTable: typeof import('./components/common/DataTable.vue')['default']
        Pagination: typeof import('./components/common/Pagination.vue')['default']
        SearchFilter: typeof import('./components/common/SearchFilter.vue')['default']
        LanguageSwitcher: typeof import('./components/common/LanguageSwitcher.vue')['default']
        ThemeToggle: typeof import('./components/common/ThemeToggle.vue')['default']
    }
}
